const CART_ITEMS = 'CART_ITEMS';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const EMPTY_CART = 'EMPTY_CART';
const ADD_QUANTITY = 'ADD_QUANTITY';
const SUB_QUANTITY = 'SUB_QUANTITY';
const GET_PRODUCTS = 'GET_PRODUCTS';
export const CART = {
  CART_ITEMS,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  EMPTY_CART,
  ADD_QUANTITY,
  SUB_QUANTITY,
  GET_PRODUCTS,
};
